### PR TITLE
pydriver: bugfixes & performance optimization

### PR DESCRIPTION
**Pull request by anuejn**
there is still a BitwiseAccessibleInteger Implementation that is not
used in pydriver for performance reasons but seemed handy to have for
other applications.

### CODE REVIEW

**Comment by rroohhh** [comment]
I added some further optimizations, these bring the time for a simple toplevel read `design.something` down to about `33us` from about `410us`.

I also tried another variant here: https://github.com/apertus-open-source-cinema/naps/commit/1651f85401ef2c68cad5310ebdfeed3056c7198e but that one is actually slightly slower.

**Review by rroohhh — DISMISSED** [review]
Your commits look fine to me

**Comment by anuejn** [comment]
I also tried to replace BitwiseAccessibleInteger with bitarray but that is also actually slower

**Review by rroohhh — APPROVED** [review]
`BitwiseAccessibleInteger` still has a somewhat weird but ssems fine.

**Pull request merged**
